# Preface {.unnumbered}

Two renowned investment advisers and authors of the bestseller *The Great Reconing* bring to light both currents of the disaster and the potential for prosperity and renewal in the face of radical changes in human history as we move into the next century. *The Sovereign Individual* details strategies necessary for adapting financially to the next phase of Western civilization.

Few observers of the late twentieth century have their fingers so presciently on the pulse of the global political and economic realignment ushering in the new millenium as do James Dale Davidson and Lord William Rees-Mogg. Their bold prediction of disaster on Wall Street in *Blood in the Streets* was borne out by Black Tuesday. In their unseuing bestseller, *The Great REckoning*, published just weeks before the coup attempt against Gorbachev, the analyzed the pending collapse of the Soviet Union and foretold the civil war in Yugoslavia and other events that have proved to be among the most searing developments of the past few years.

In *The Sovereign Individual*, Davidson and Rees-Mogg explore the greatest economic and political transition in centuries --- the shift from an industiral to an information-based society. This transition, which they have termed "the fourth stage of human society", will liberate individuals as never before, irrevocably altering the power of government. This outstanding book will replace false hopes and fictions with new understanding and clarified values.
